### ISSUE TITLE
Button text not visible while selecting the avatar in landscape mode.

### ISSUE THREAD

**Issue by harshitagupta30** [systers/powerup-android#289] opened 2017-01-28 13:12 UTC
**Current Behaviour**

![screenshot_2017-01-28-18-32-55](https://cloud.githubusercontent.com/assets/12701036/22396823/47494ac8-e589-11e6-9979-803fdf864aaa.png)
![screenshot_2017-01-28-18-32-57](https://cloud.githubusercontent.com/assets/12701036/22396820/47419472-e589-11e6-90b1-fccf2cd078ff.png)
![screenshot_2017-01-28-18-32-43](https://cloud.githubusercontent.com/assets/12701036/22396821/47453f96-e589-11e6-99a4-888ce37289c1.png)
![screenshot_2017-01-28-18-32-47](https://cloud.githubusercontent.com/assets/12701036/22396822/4745c7f4-e589-11e6-8a54-33030adfa2ea.png)

@chhavip @anubhakushwaha Can I work on this issue?

**Comment by anubhakushwaha** [comment] 2017-01-28 15:13
@harshitagupta30 You got this bug after running on which branch? as I can't reproduce this bug

**Comment by harshitagupta30** [comment] 2017-01-28 15:14
@anubhakushwaha I am currently on develop branch.

**Comment by himani777** [comment] 2017-01-28 15:31
@anubhakushwaha I also witnessed same bug after cloning from develop branch.

**Comment by anubhakushwaha** [comment] 2017-01-28 17:26
Yeah, can go ahead ,also make sure that the buttons re-align properly along with equal sizes for each button in all activities.

**Comment by HimanshuS01** [comment] 2017-01-28 19:58
@harshitagupta30 @himani777 @anubhakushwaha I think that is happening after the last PR got merged ,as button text is clearly visible in landscape mode too before the last PR.

**Closed** 2017-05-12 20:28 UTC
