### ISSUE TITLE
SessionHistory.eyesTotalNo does not match the number of eyes drawables

### ISSUE THREAD

**Issue by Ph0ebe** [systers/powerup-android#797] opened 2017-12-31 18:05 UTC
## Description
The SessionHistory.eyesTotalNo is set to 9 by default in the AvatarRoomActivity, the eye variable can reach this value however, this is then used to identify a drawable to display and there are only 7 eyes drawables.

## Mocks
![eyesdrawable](https://user-images.githubusercontent.com/24575179/34463462-aaba2396-ee54-11e7-8d7a-fe9cb28bf480.PNG)
![sessionhistory](https://user-images.githubusercontent.com/24575179/34463463-b0109bb8-ee54-11e7-8458-f07842b764cf.PNG)
As you can see, the first image shows the number of eye drawables that exist and the second image shows the SessionHistory.eyesTotalNo.
## Acceptance Criteria
You can either introduce two new drawables for eyes8 and eyes9 or you can change the SessionHistory to reflect only 7 drawables.
### Update [Required]
- [x] Ensure SessionHistory matches number of drawables

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by isabelcosta** [comment] 2018-03-18 22:18
@MeepyMay I just want to highlight one of the effects of this bug is that when an image of the eyes isn't found.

- This does not have a direct impact on the AvatarRoom screen, because the eyes simply aren't replaced.
- But this affects when we go to the Store screen, because when the avatar is created from what is saved on the DB, the image does not exist hence does not appear.

Example:

![image](https://user-images.githubusercontent.com/11148726/37571848-0504628a-2afa-11e8-80f9-59dc586f8326.png)

**Comment by Rimjhim28** [comment] 2018-03-19 04:50
@isabelcosta The issue is already solved through PR #511 . The PR is yet to be merged.

**Comment by isabelcosta** [comment] 2018-03-19 10:53
Thank you for telling me about the PR @Rimjhim28 
I just wanted to highlight the effects of this bug, since the PRs referenced here were from the last year.

**Closed** 2018-04-19 18:58 UTC
Labels: Program: GCI
