### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by nidhinmahesh** [systers/powerup-android#1326] opened 2019-01-25 05:53 UTC
## Description
I need to add Chinese translation to Power Up app.

Smartphone users in China were predicted to account for around 56 percent of all mobile phone users in 2017. This figure is expected to grow to more than 60 percent by 2019. Android is also the most popular operating system among Chinese smartphone users, with almost 80 percent of the share as of July 2017.

User base of the app will be expanded. 

### Update [Required]
- [ ]  new strings file for Chinese language.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by nidhinmahesh** [comment] 2019-01-25 05:54
may I work on this issue

**Comment by Rimjhim28** [comment] 2019-01-25 09:21
Hello @nidhinmahesh! 
Since this is an enhancement to the project rather than a technical issue, could you please initiate a discussion about this on #powerup in Systers community slack channel so that we can have inputs from other community members as well before you work on this issue.
Link to join Slack Channel Inviter: systers.io/slack-systers-opensource/

**Comment by nidhinmahesh** [comment] 2019-01-25 13:42
> Hello @nidhinmahesh!
> Since this is an enhancement to the project rather than a technical issue, could you please initiate a discussion about this on #powerup in Systers community slack channel so that we can have inputs from other community members as well before you work on this issue.
> Link to join Slack Channel Inviter: systers.io/slack-systers-opensource/

Certainly!

**Comment by Rimjhim28** [comment] 2019-01-29 18:52
Since the issue is not high priority, I am closing it.
It can be worked upon after the game has actual data.
Reference: https://systers-opensource.slack.com/archives/C0C9VK8UE/p1548608573053100?thread_ts=1548423803.041500&cid=C0C9VK8UE

**Closed as completed** 2019-01-29 18:52 UTC
Labels: Type: Enhancement, Priority: LOW, OPEN LATER
