### ISSUE TITLE
[Bug] Unable to deselect an accessory once selected in store

### ISSUE THREAD

**Issue by yatna** [systers/powerup-android#368] opened 2017-04-20 19:44 UTC
In the store, under the 'Accessories' section, it is impossible to deselect an accessory once selected for the avatar. User is either forced to go back or purchase that accessory.
Steps to reproduce the bug:
1.) Go the accessory section with an avatar  neither having a 'Bag' or 'Hat'.
2.) Now select any one 'Hat' and one 'Bag'
3.) Now try to purchase only the 'Bag' without the 'Hat'. Its impossible as we can't de-select the 'Hat'. We will have to go back to remove the selected choices and then reselect.
I would like to work on this @aanchal07

**Comment by codingblazer** [comment] 2017-04-20 19:46
@yatna This is duplicate of #283

**Closed** 2017-04-20 19:50 UTC
