### ISSUE TITLE
Absence of 'ImageButton' for 'Necklace' accessory experienced in API levels 18 , 19 having low screen sizes

### ISSUE THREAD

**Issue by sashafierce** [systers/powerup-android#352] opened 2017-03-14 05:33 UTC
left and right ImageButtons absent for 'Necklace' accessory which prevents it from getting selected.
Experienced on API levels - 18(screen sizes - 4.65 , 4.7) , 19 (screen sizes - 4.65 , 4.7)
Note : Behavior was uniform for other API levels over different screen sizes.

<a href="url"><img src= "https://cloud.githubusercontent.com/assets/18103181/23887031/316abd24-08a5-11e7-9380-400b2b9ad07b.png" align="left" height="600" width="350" ></a>

**Comment by mahikaw** [comment] 2017-03-21 14:17
@aanchal07 @chhavip Can I submit a PR for this?

**Comment by codingblazer** [comment] 2017-03-21 14:32
@mahikaw @sashafierce This issue is duplicate of #326 . The problem has no relation with the API level. Its happening because of low screen size.

**Comment by mahikaw** [comment] 2017-03-21 14:35
oh. I see. @codingblazer, so you say this can't be solved?

**Comment by codingblazer** [comment] 2017-03-21 14:38
@mahikaw 
1. The issue is duplicate of #326 
2. Issue is wrong. Imagebutton are present for all API levels. This problem is because of small screen sizes only and thus API level as cause is wrongly mentioned in the issue.
@mahikaw This can be solved for sure. I have solved it actually under issue #326 and am waiting for mentors approval. :-)

**Comment by mahikaw** [comment] 2017-03-21 14:41
oh okay, that's great. good job!
@sashafierce please close this issue. :smile:

**Comment by sashafierce** [comment] 2017-03-22 15:25
@codingblazer  I tested it on higher API levels and did not experience the same. And i thought its better to be specific about the API level I tested it on

**Comment by codingblazer** [comment] 2017-03-22 16:09
@sashafierce Yeah, API level can definitely have effect on layout but not in this case as ImageButton were added in API level 1 (i guess so). So, this issue can't be because of API level.
@sashafierce Feel free to ask any doubts. Happy Coding :-)

**Closed** 2017-03-23 11:28 UTC
