### ISSUE TITLE
Addition of Feature: Education on sanitary napkins

### ISSUE THREAD

**Issue by swaroop-nath** [systers/powerup-android#1086] opened 2018-03-19 12:42 UTC
I have played the entire game in order to have an overview and felt that there should be a feature where
the users are taught about the benefits of using sanitary napkins.

I am from India and according to surveys conducted, almost 58% of total women population have access to sanitary napkins (Source: https://thelogicalindian.com/health/menstruation-in-rural-india/)

I feel that including this feature to the game will be pretty beneficial for preadolescent girls.

I was hoping to submit it as a project proposal in GSoC 2018. Can I go ahead?

**Comment by Rimjhim28** [comment] 2018-03-19 12:49
@swaroop-nath This is new feature, that is, a kind of enhancement. It's better if you first discuss it on the community channel rather than proceeding to create an issue.
Also, for creating any issue , please follow the issue template that comes by default.

**Comment by swaroop-nath** [comment] 2018-03-19 12:53
Ok, So I can discuss it on Slack?

**Comment by Rimjhim28** [comment] 2018-03-19 12:56
Yes exactly! You can discuss any of the new ideas and enhancements on slack (it is recommended to do so).
Also, since this issue of yours is not a bug that needs to fixed, you can close this for now.
For any new issue, please follow the issue template.

**Comment by swaroop-nath** [comment] 2018-03-19 12:57
Ok, I will keep that in mind. Thanks :)

**Closed** 2018-03-19 12:57 UTC
