### ISSUE TITLE
Translations for the app in Malayalam.

### ISSUE THREAD

**Issue by hridyakrishna** [systers/powerup-android#1322] opened 2019-01-21 13:17 UTC
## Description
As a user, I need to translate the app in Malayalam, so that everyone can use the app in Malayalam.

### Update [Required]
- [x] [powerup-android/PowerUp/app/src/main/res/values-ml/strings.xml]

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
48 hours

**Comment by hridyakrishna** [comment] 2019-01-21 13:18
May I please work on this issue?

**Comment by Rimjhim28** [comment] 2019-01-25 09:27
Hello @hsymphonyk!
Since this is an enhancement to the project rather than a technical issue, could you please initiate a discussion about this on #powerup in Systers community slack channel so that we can have inputs from other community members as well before you work on this issue.
Link to join Slack Channel Inviter: systers.io/slack-systers-opensource

Also, go through the Contribution guidelines once. Please create a PR only after the issue is approved and assigned to you by any of the maintainers. :)

**Comment by hridyakrishna** [comment] 2019-01-28 11:52
Hello, @Rimjhim28  Yes, I will start a discussion about it on the #powerup channel.
Sure, I will go through the Contribution guidelines and will take care of giving pull requests only after approval, from now. Thank you.

**Comment by Rimjhim28** [comment] 2019-01-29 18:51
Since the issue is not high priority, I am closing it.
It can be worked upon after the game has actual data.
Reference: https://systers-opensource.slack.com/archives/C0C9VK8UE/p1548608573053100?thread_ts=1548423803.041500&cid=C0C9VK8UE

**Closed as completed** 2019-01-29 18:52 UTC
Labels: Type: Enhancement, Priority: LOW, OPEN LATER
