### ISSUE TITLE
Use buttons with background images in StartActivity

### ISSUE THREAD

**Issue by m-sameer** [systers/powerup-android#944] opened 2018-01-14 14:34 UTC
## Description
Presently, a PNG image is used in StartActivity as background with transparent buttons drawn on top of it. The PNG image must be replaced with another PNG image only with background and PowerUp logo.  Buttons with background color or image must be used in the XML file. By doing so we can also add material design ripple effect to the buttons. Also, the following code (which sets the text of "Load" button to "Resume") will then work in StartActivity which is not working presently:
```java
@Override
    protected void onResume() {
        super.onResume();
        hasPreviouslyStarted = preferences.getBoolean(getString(R.string.preferences_has_previously_started), false);
        if (hasPreviouslyStarted) {
            startButton.setText(getString(R.string.resume_text));
        }
    }
```
This will also improve the performance as then there will be no use of weights which are bad for performance.
## Acceptance Criteria
- The transparent buttons must be replaced with buttons with the background like that of buttons now so that the appearance doesn't change.
- The present PNG image must be replaced by another PNG **without** buttons and with only background and PowerUp logo.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours

**Comment by m-sameer** [comment] 2018-01-14 14:34
@codingblazer @Rimjhim28 Please review the issue. :)

**Comment by AjaySharvesh3** [comment] 2018-03-30 12:38
Can I solve this issue? @codingblazer @Rimjhim28

**Comment by Rimjhim28** [comment] 2018-03-30 14:25
The issue is not approved. We need to discuss more on this.

**Comment by Rimjhim28** [comment] 2018-08-12 18:37
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.

**Closed by Rimjhim28** 2018-08-12 18:37 UTC
Labels: OPEN LATER
