### ISSUE TITLE
new situations and scenarios

### ISSUE THREAD

**Issue by mahikaw** [systers/powerup-android#203] opened 2016-12-13 09:51 UTC
I think some new scenarios/situations need to be added to the app, which address other problems as well and hence, creates awareness.

**Comment by chhavip** [comment] 2016-12-14 06:43
Good idea. We are looking for the same, please suggest some that you would like to incorporate.

**Comment by mahikawason** [comment] 2016-12-14 07:08
I think the following issues can be addressed in a similar way as before( situation-based learning)

**1. Social Coercion** This can be done by creating situation where Rosie's boyfriend says stuff like:

- "Let's have sex, everybody’s doing it.", "Sex is the way to prove that you love me" and so on. Where Rosie can respond in the following ways: " I really like you but I'm not ready", "If you love me you will respect my decision" or "okay, just because you say so" and so on.

 **2. Sexual Abuse** This could incorporate situations of sexual abuse and how Rosie will deal with them. Will she share it with her parents or will she just bear it.

**Comment by mahikawason** [comment] 2016-12-14 07:21
**Mini Games:**
We include games for sex education, for example the app will throw descriptions of a certain word to the user and the user has to guess that word and select it from a set odf options provided. In this way, she will get to know more about sex, reproduction, puberty etc.
Next, could be a puzzle game where from a block of randomly placed letters, she will have to find specific words( which will be again related to topics of our interest) and then maybe, as soon as she identifies a word, the screen flashes with the meaning and significance of it.

**Comment by chhavip** [comment] 2016-12-15 14:02
Quite good suggestions! Will be kept in mind during the next expansion of the application.

**Comment by aanchal07** [comment] 2017-05-12 18:52
New scenarios and mini games will be added after discussing with the team managers.

**Closed by aanchal07** 2017-05-12 18:52 UTC
