### ISSUE TITLE
Opening of the wrong scene after the entire game is played once

### ISSUE THREAD

**Issue by ShriyaSalian** [systers/powerup-android#924] opened 2018-01-11 20:45 UTC
## Description
After a full-run of the game, when the first scene (home) is clicked again, the library scene is displayed instead of the home scene.

## Replication of Issue

[vid_powerup.zip](https://github.com/systers/powerup-android/files/1624051/vid_powerup.zip)

### Update [Required]
- [ ]The above mentioned bug is fixed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
18-20 hours 

@codingblazer @aanchal07  @MeepyMay  Kindly review, I would like to work on this.

**Comment by Rimjhim28** [comment] 2018-01-12 04:53
@ShriyaSalian  The issue is already open in #500 which is approved and a PR is also sent. Since this is duplication you can better close it.
Please go through all the open issues to avoid any trouble.

**Closed** 2018-01-12 18:27 UTC
