### ISSUE TITLE
'PowerUpDemoContent' scenario appears after the last scenario i.e. 'School'

### ISSUE THREAD

**Issue by sashafierce** [systers/powerup-android#351] opened 2017-03-13 15:39 UTC
After consulting 'GameActivity.java' and 'Scenario.csv' I realised that GameOverActivity is supposed to follow after the last scenario which is 'School' (id = 7) but instead  'PowerUpDemoContent' (id = 1) flashes in between for a very short time.

<a href="url"><img src= "https://cloud.githubusercontent.com/assets/18103181/23861437/07065540-0830-11e7-95ce-d0cbc2220344.png" align="left" height="600" width="350" ></a>

**Comment by sashafierce** [comment] 2017-03-13 15:45
@anubhakushwaha @chhavip @aanchal07  Can I send a PR? :)

**Comment by codingblazer** [comment] 2017-03-13 16:24
@sashafierce This is a duplicate of #310 . please close this issue as it will be handled in next development cycle :-)

**Closed** 2017-03-13 16:44 UTC
