### ISSUE TITLE
Audio for Button OnClick()

### ISSUE THREAD

**Issue by AjaySharvesh3** [systers/powerup-android#1108] opened 2018-04-15 03:26 UTC
## Description
As a maintainer,
I need to add an audio for the button,
so that the app will more be entertained and looks great.
## Mocks
Not Applicable

### Update [Required]
- [ ] Adding audio files to raw folder
- [ ] Implementing the audio to the buttons onClick() method.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by AjaySharvesh3** [comment] 2018-04-15 03:28
@m-murad @geekanamika @Rimjhim28 @MeepyMay Can you please give me the approval for this?

**Comment by geekanamika** [comment] 2018-04-16 18:08
@AjaySharvesh3 It's not a bug fix. Let's discuss it in slack/open session?

**Comment by AjaySharvesh3** [comment] 2018-04-17 05:31
@geekanamika Sure, let's discuss that.

**Comment by Rimjhim28** [comment] 2018-08-12 19:03
This is an enhancement. I am closing the issue for now. It can be opened and worked on after discussion on community channel.

**Closed by Rimjhim28** 2018-08-12 19:03 UTC
Labels: OPEN LATER, Priority: LOW, Type: Enhancement
