### ISSUE TITLE
Reverting to No Accessories in SelectFeaturesActivity

### ISSUE THREAD

**Issue by BaaniLeen** [systers/powerup-android#355] opened 2017-03-19 05:01 UTC
![selectfeatureserror1](https://cloud.githubusercontent.com/assets/22029744/24078246/d251c718-0c8e-11e7-8df2-fad322186a70.png)

Currently after trying out the accesories, the user cannot unselect his choice and revert back to the No Accessory (eg. No Bag or no Glasses) phase.

@chhavip @aanchal07  Can I work on this issue?
Thanks!

**Comment by codingblazer** [comment] 2017-03-19 05:05
Hey, this is duplicate of #283. Please close this issue :-)

**Comment by BaaniLeen** [comment] 2017-03-19 05:21
@codingblazer Okay..! :)

**Comment by mahikaw** [comment] 2017-03-21 14:12
@BaaniLeen Please close this issue. :smile:

**Closed** 2017-03-21 14:45 UTC
