### ISSUE TITLE
Enhancement: Karma notifier

### ISSUE THREAD

**Issue by top-gun007** [systers/powerup-android#337] opened 2017-02-18 19:36 UTC
**Summary**
During game play every karma points player gains/looses after making a choice he/she should be notified about it(in form of toast or something else) so that they could figure out which choices are good to do in real life.

like for eg:-
![image](https://cloud.githubusercontent.com/assets/15179401/23096304/43481ece-f63f-11e6-848a-f1fb94e9b67a.png)

In this instance if the user chooses 1st option a message would be displayed like _Karma Points +2_ and if he/she chooses 2nd one then another one would be displayed saying _Karma Points +1_ 

_Right now we have only one scenario so its effect wont be that significant but in future when we would be having multiple scenarios it would certainly help the cause._

**Comment by HimanshuS01** [comment] 2017-02-18 21:49
hey @top-gun007 I think This issue is a duplicate of #172 that was opened
by @anubhakushwaha <https://github.com/anubhakushwaha> ,the PR of which has
already been created in #199 by @InfernoCoder
<https://github.com/InfernoCoder> .

**Comment by top-gun007** [comment] 2017-02-19 08:20
hello @HimanshuS01 I beg your pardon but the two issues are totally different and both issues can be integrated in sync with each other because of the following reason:

- mine deals only with telling the user how many points he/she have gained by making a decision and on the contrary the other issue warns the user about the choice he/she is making not the points the user had made.
_Thank you for showing concern_

**Comment by top-gun007** [comment] 2017-03-03 22:48
please review this issue @anubhakushwaha @chhavip @aanchal07 .
_Thank you_

**Comment by aanchal07** [comment] 2017-03-22 05:42
@top-gun007 Do you want to show a toast when a user clicks the answer and before going to the next screen? Please make the functionality clear.

**Comment by top-gun007** [comment] 2017-03-23 09:58
Thank you for looking into it.
I propose two things:
1- Create a karma points would be shown on every screen of the app not just on the store area.
2- after every selection the corresponding increase and decrease in karma points would be seen originating from the selection menu and from there it would animate/move to the karma points and fade away and in the mean while the karma pointer is updated.

For this the animation part I propose to use TweenAnimations.

**Comment by aanchal07** [comment] 2017-03-24 11:20
@top-gun007 The karma points are shown after each scenario gets completed and not on the game activity screen. This change would lead to change in game mechanics. I am asking the project manager about the same and will let you know.

**Closed** 2017-05-12 19:16 UTC
